// Declarations to ensure HTML element interfaces are included in TypeDoc output
// These mirror the autogenerated Stencil HTML element interfaces so docs include them

declare global {
  interface HTMLUiButtonElement extends HTMLElement {}
  interface HTMLUiCalendarElement extends HTMLElement {}
  interface HTMLUiCheckboxElement extends HTMLElement {}
  interface HTMLUiHeadingElement extends HTMLElement {}
  interface HTMLUiNumberPickerElement extends HTMLElement {}
  interface HTMLUiSliderElement extends HTMLElement {}
  interface HTMLUiTextElement extends HTMLElement {}
  interface HTMLUiToggleElement extends HTMLElement {}

  // (EventMap interfaces are defined in the autogenerated components.d.ts)
}

export {};
