export type AttributeSchema = {
  type: 'string' | 'number' | 'boolean' | 'enum';
  options?: string[];
  description?: string;
};

export const ATTRIBUTE_SCHEMAS: Record<string, Record<string, AttributeSchema>> = {
  'ui-button': {
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme for the button' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'keyboard': { type: 'boolean', description: 'Enable keyboard navigation' },
    'label': { type: 'string', description: 'Text label displayed on the button' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'variant': { type: 'enum', options: ['filled', 'minimal', 'outlined'], description: 'Visual style variant' },
  },
  'ui-toggle': {
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme for the active state' },
    'connected': { type: 'boolean', description: 'Connection state for read-only monitoring' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'keyboard': { type: 'boolean', description: 'Enable keyboard navigation' },
    'label': { type: 'string', description: 'Text label displayed left to the toggle' },
    'readonly': { type: 'boolean', description: 'Read only mode, display value but prevent changes' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'value': { type: 'boolean', description: 'Current boolean value of the toggle' },
    'variant': { type: 'enum', options: ['apple', 'circle', 'cross', 'neon', 'square'], description: 'Visual style variant' },
  },
  'ui-checkbox': {
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme for the active state' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'keyboard': { type: 'boolean', description: 'Enable keyboard navigation' },
    'label': { type: 'string', description: 'Text label displayed right to the checkbox' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'value': { type: 'boolean', description: 'Current boolean value of the checkbox' },
    'variant': { type: 'enum', options: ['filled', 'minimal', 'outlined'], description: 'Visual style variant' },
  },
  'ui-slider': {
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme for the active state' },
    'connected': { type: 'boolean', description: 'Connection state for read-only monitoring' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'keyboard': { type: 'boolean', description: 'Enable keyboard navigation' },
    'label': { type: 'string', description: 'Text label displayed above the slider' },
    'max': { type: 'number', description: 'Maximum allowed value' },
    'min': { type: 'number', description: 'Minimum allowed value' },
    'orientation': { type: 'enum', options: ['horizontal', 'vertical'], description: 'Orientation of the slider' },
    'readonly': { type: 'boolean', description: 'Read only mode, display value but prevent changes' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'step': { type: 'number', description: 'Step increment/decrement amount' },
    'thumb-shape': { type: 'enum', options: ['arrow', 'circle', 'diamond', 'square', 'triangle'], description: 'Shape of the slider thumb' },
    'value': { type: 'number', description: 'Current numeric value of the slider' },
    'variant': { type: 'enum', options: ['narrow', 'neon', 'rainbow', 'stepped', 'wide'], description: 'Visual style variant' },
  },
  'ui-number-picker': {
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme for the active state' },
    'connected': { type: 'boolean', description: 'Connection state for read-only monitoring' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'keyboard': { type: 'boolean', description: 'Enable keyboard navigation' },
    'label': { type: 'string', description: 'Text label displayed above the number picker' },
    'max': { type: 'number', description: 'Maximum allowed value' },
    'min': { type: 'number', description: 'Minimum allowed value' },
    'readonly': { type: 'boolean', description: 'Read only mode, display value but prevent changes' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'step': { type: 'number', description: 'Step increment/decrement amount' },
    'value': { type: 'number', description: 'Current numeric value of the number picker' },
    'variant': { type: 'enum', options: ['filled', 'minimal', 'outlined'], description: 'Visual style variant' },
  },
  'ui-text': {
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme for the active state' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'debounce-ms': { type: 'number', description: 'Debounce delay in milliseconds for editable mode updates' },
    'label': { type: 'string', description: 'Text label displayed above the text display' },
    'max-length': { type: 'number', description: 'Maximum character limit (editable mode only)' },
    'max-rows': { type: 'number', description: 'Maximum number of rows for area mode' },
    'min-rows': { type: 'number', description: 'Minimum number of rows for area mode' },
    'mode': { type: 'enum', options: ['area', 'editable', 'field', 'structured', 'unstructured'], description: 'Display mode for the text component' },
    'placeholder': { type: 'string', description: 'Placeholder text shown when value is empty (editable mode only)' },
    'resizable': { type: 'boolean', description: 'Enable text area resizable' },
    'show-char-count': { type: 'boolean', description: 'Show character count' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-line-numbers': { type: 'boolean', description: 'Show line numbers' },
    'show-save-button': { type: 'boolean', description: 'Show save button for explicit updates (editable mode only)' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'value': { type: 'string', description: 'Current text value of the component' },
    'variant': { type: 'enum', options: ['filled', 'minimal', 'outlined'], description: 'Visual style variant' },
  },
  'ui-calendar': {
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme for the active state' },
    'connected': { type: 'boolean', description: 'Connection state for readonly mode' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'first-day-of-week': { type: 'enum', options: ['0', '1'], description: 'First day of week (0 = Sunday, 1 = Monday)' },
    'include-time': { type: 'boolean', description: 'Include time picker alongside date picker' },
    'inline': { type: 'boolean', description: 'Display calendar inline instead of as a popup' },
    'keyboard': { type: 'boolean', description: 'Enable keyboard navigation' },
    'label': { type: 'string', description: 'Text label displayed above the calendar' },
    'max-date': { type: 'string', description: 'Maximum selectable date (ISO string)' },
    'min-date': { type: 'string', description: 'Minimum selectable date (ISO string)' },
    'show-clear-button': { type: 'boolean', description: 'Show clear button to reset selection' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'show-today-button': { type: 'boolean', description: 'Show today button' },
    'show-week-numbers': { type: 'boolean', description: 'Show week numbers in calendar grid' },
    'time-format': { type: 'enum', options: ['12', '24'], description: 'Time format when includeTime is enabled' },
    'value': { type: 'string', description: 'Current date-time value of the calendar (ISO string)' },
    'variant': { type: 'enum', options: ['filled', 'outlined'], description: 'Visual style variant' },
  },
  'ui-color-picker': {
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'label': { type: 'string', description: 'Text label displayed right to the color picker' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'value': { type: 'string', description: 'Current color value in hex format (e.g., #ff0000)' },
  },
  'ui-file-picker': {
    'accept': { type: 'string', description: 'File type restrictions (e.g., ".pdf,.doc", "image/*")' },
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme for the active state' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'label': { type: 'string', description: 'Text label displayed above the file picker' },
    'max-files': { type: 'number', description: 'Maximum number of files when multiple is true' },
    'max-size': { type: 'number', description: 'Maximum file size in bytes' },
    'multiple': { type: 'boolean', description: 'Whether multiple files can be selected' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
  },
  'ui-event': {
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme for the active state' },
    'connected': { type: 'boolean', description: 'Connection status indicator' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'event-name': { type: 'string', description: 'Event name to subscribe to (for identification/display purposes)' },
    'keyboard': { type: 'boolean', description: 'Enable keyboard navigation' },
    'label': { type: 'string', description: 'Text label displayed above the event listener' },
    'max-events': { type: 'number', description: 'Maximum number of events to keep in history' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'show-timestamp': { type: 'boolean', description: 'Show event timestamps' },
    'variant': { type: 'enum', options: ['filled', 'outlined'], description: 'Visual style variant' },
  },
  'ui-notification': {
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'duration': { type: 'number', description: 'Duration before auto-dismiss (0 to disable auto-dismiss)' },
    'message': { type: 'string', description: 'The message text to display in the notification' },
    'show-close-button': { type: 'boolean', description: 'Whether to show a close button' },
    'show-icon': { type: 'boolean', description: 'Whether to show an icon based on the notification type' },
    'type': { type: 'enum', options: ['error', 'info', 'success', 'warning'], description: 'Type of notification for different visual styling and icons' },
  },
  'ui-object': {
    'color': { type: 'enum', options: ['neutral', 'primary', 'secondary'], description: 'Color theme' },
    'dark': { type: 'boolean', description: 'Enable dark mode theme styling' },
    'disabled': { type: 'boolean', description: 'Disable user interaction' },
    'label': { type: 'string', description: 'Optional label shown above the editor' },
    'readonly': { type: 'boolean', description: 'Read only mode' },
    'show-last-updated': { type: 'boolean', description: 'Show last updated timestamp' },
    'show-status': { type: 'boolean', description: 'Show visual operation status indicators' },
    'variant': { type: 'enum', options: ['filled', 'outlined'], description: 'Visual style for the editor container' },
  },
};

export function getAttributeSchema(componentType: string): Record<string, AttributeSchema> {
  return ATTRIBUTE_SCHEMAS[componentType] || {};
}
